### PR TITLE
feat(api): 2775 - Override config from environment

### PR DESCRIPTION
**Pull request by pitiscarf**
[2775](https://www.notion.so/jeveuxaider/Override-api-config-from-environment-7be256eb503f4383ac5971c3a3c2ab45)

### CODE REVIEW

**Review by pierre-lebihan — DISMISSED** [review]
ok

**Comment by pierre-lebihan** [comment]
Custom env down

**Comment by pitiscarf** [comment]
> Custom env down


admin_endpoint = "https://snucustomz3ln7wxn-env-overwrite-admin.functions.fnc.fr-par.scw.cloud/"
api_endpoint = "https://snucustomz3ln7wxn-env-overwrite-api.functions.fnc.fr-par.scw.cloud/"
app_endpoint = "https://snucustomz3ln7wxn-env-overwrite-app.functions.fnc.fr-par.scw.cloud/"

**Review by michaelgarcia75 — APPROVED** [review]
Bon boulot !

**Pull request merged**
